### ISSUE TITLE
Issue when running the code

### ISSUE THREAD

**Issue by staceycy** [JavonneM/BlenderToRGBD#5] opened 2019-07-22 12:03 UTC
Hi, 
Thank you very much for sharing your codes. 
I tried to run your code with blender file attached with following command:
`blender 28911.blend -b -P generateRGBD.py -- ./test/ -r`

However, it gives following error:
'''
Traceback (most recent call last):
  File "/hdd1/open6d/rendering_blender/BlenderToRGBD/generateRGBD.py", line 483, in <module>
    main()
  File "/hdd1/open6d/rendering_blender/BlenderToRGBD/generateRGBD.py", line 474, in main
    depth_maps, all_translations, all_rotations, timestamps = animation(render=render)
  File "/hdd1/open6d/rendering_blender/BlenderToRGBD/generateRGBD.py", line 353, in animation
    depthMap = get_depth_map()
  File "/hdd1/open6d/rendering_blender/BlenderToRGBD/generateRGBD.py", line 235, in get_depth_map
    red = zBuffer[index]
IndexError: index 263680 is out of bounds for axis 0 with size 262144
'''

This is caused by the face that the length of pixels from Viewer:
`pixels = bpy.data.images['Viewer Node'].pixels`
 is fixed at 262144 regardless of the size of rendered image. 

Do you have any suggestions on how to solve this problem? 
[28911.blend.zip](https://github.com/JavonneM/BlenderToRGBD/files/3417228/28911.blend.zip)

Thanks a lot. 
Stacey

**Comment by JavonneM** [comment] 2019-07-23 08:42
I'll take a look at this later today, currently it's set to reproduce the image size created during the registration process of the Kinect V2. I'll add input parameters to change the resolutions and a parameter to use the resolution specified in Blenders camera.

**Comment by staceycy** [comment] 2019-07-23 08:47
@JavonneM Thank you very much for your quick reply. 

I think the problem may come from that the resolution in the viewer is different from the rendered output. However, I am quite new to blender, so I haven't figure out how to solve this problem. 

Thanks and looking forward to your reply :grin:

**Comment by JavonneM** [comment] 2019-07-23 08:51
Ah, so you might want to ensure that the rendered image doesn't have a scale factor applied. By default in blender you can set the rendered image to something but after rendering a factor is applied that downscales it. Please note the percentage under the resolution, ensure that the resolution is set to 640X480 and the percentage is 100%.
https://blender.stackexchange.com/a/3474

Are you trying to render a different resolution ?

**Comment by staceycy** [comment] 2019-07-23 08:58
@JavonneM Thanks for your suggestion. 

Actually, I have done as you suggested: the resolution is set to 640X480 and the percentage is 100%. However, the resolution in the viewer node is 256*256, which cause the problem.

**Comment by JavonneM** [comment] 2019-07-23 19:16
Turns out running the blender in background mode completely breaks the rendering/composite layer when accessing the pixels. This defaults the resolution to 512 * 512 = 262144 . Please try rendering without the `-b` option. Instead of `blender 28911.blend -b -P generateRGBD.py -- ./test/ -r` try `blender 28911.blend -P generateRGBD.py -- ./test/ -r`.
Still investigating for a proper fix for this, but I think I couldn't find a proper solution when I was doing my masters degree, will verify.

**Comment by staceycy** [comment] 2019-07-25 01:04
@JavonneM 
Thanks for your suggestions. Without the -b option, the code can run successfully. 
I will also try to explore, and do keep in touch :)

**Closed as completed** 2019-07-27 18:36 UTC
